# Change these first
owner: yamikaitou # Your GitHub username
repo: status # Your GitHub repository name

# Add your sites here
sites:
  - name: SCGC Panel
    url: https://panel.scgc.xyz

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.yamikaitou.dev
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
